import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/world">my World!</Link>
        </h1>

        <p className={styles.description}>World description</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.character.xyz"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div className="grid gap-1 grid-cols-1 grid-rows-2 items-center">
            <p className="w-full text-center"> Powered by{""}</p>
            <span>
              <Image
                src="/characterxyz_logo.png"
                alt="Character XYZ Logo"
                width={106}
                height={32}
              />
            </span>
          </div>
        </a>
      </footer>
    </div>
  );
};

export default Home;
